name: React-Build
on: [push, workflow_dispatch]
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout The code
        uses: actions/checkout@v3

      - name: Install Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Run test
        run: npm test
  
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout The code
        uses: actions/checkout@v3

      - name: Install Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build
      
      - name: Deploy 
        run: echo "Code deployed"